// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4X_U4bC26-aC4oUG5fcIBwFN8qQQK0U4',
    appId: '1:950254744378:web:f99dff4acaa60908011603',
    messagingSenderId: '950254744378',
    projectId: 'escola-ruis',
    authDomain: 'escola-ruis.firebaseapp.com',
    databaseURL: 'https://escola-ruis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'escola-ruis.appspot.com',
    measurementId: 'G-3YZHQ7G3HY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHnjE-z0kily2AwirHHOi6EGivxczXiXY',
    appId: '1:950254744378:android:91c8fd8e25566ecb011603',
    messagingSenderId: '950254744378',
    projectId: 'escola-ruis',
    databaseURL: 'https://escola-ruis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'escola-ruis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd6PXgCwy5YfQ4bHdPVucgaJbNzs7dJnE',
    appId: '1:950254744378:ios:35498eebceb12797011603',
    messagingSenderId: '950254744378',
    projectId: 'escola-ruis',
    databaseURL: 'https://escola-ruis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'escola-ruis.appspot.com',
    iosClientId: '950254744378-dn8egb2gmc29d6a60muct86qk01g4tvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd6PXgCwy5YfQ4bHdPVucgaJbNzs7dJnE',
    appId: '1:950254744378:ios:35498eebceb12797011603',
    messagingSenderId: '950254744378',
    projectId: 'escola-ruis',
    databaseURL: 'https://escola-ruis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'escola-ruis.appspot.com',
    iosClientId: '950254744378-dn8egb2gmc29d6a60muct86qk01g4tvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoss',
  );
}
